/**
 * Nostrom mark: the letter "N" traced by a single proof-of-life pulse.
 *
 * A flat baseline enters from the left, spikes to the apex, falls through the
 * long diagonal to the lowest point, rises into the right stem and flatlines
 * out the other side; the glyph *is* the protocol. The N's left stem is a
 * separate bar with a diagonally cut top, so a hairline of background separates
 * it from the falling diagonal — that notch is part of the artwork, not a gap to
 * be closed.
 *
 * Two subpaths, 39 vertices, generated by `scripts/vectorise-logo.py` from the
 * brand artwork and verified at 99.5% IoU against the source raster. The
 * previous path was traced at 200px and thinned by dropping nearby points, which
 * turned every straight edge into a 1px staircase — 200+ vertices that rendered
 * visibly lumpy. Do not hand-edit: re-run the script if the artwork changes.
 *
 * Colour comes from `currentColor`. The mark is achromatic (white) by design:
 * this palette spends green, amber and red exclusively on vault liveness, so a
 * coloured logo would imply a status it cannot have.
 */
export function Logo({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 64 31.46"
      className={className}
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <path
        fill="currentColor"
        d="M63.88 15.25L61.72 18.49L51.03 18.49L50.19 19.45L41.79 30.98L41.43 31.34L41.19 31.34L40.47 30.62L33.38 21.01L24.02 8.77L23.41 9.37L18.13 17.05L17.41 17.89L0 17.89L0 13.93L14.17 13.93L15.13 12.73L15.49 12.01L23.29 0.6L23.77 0L24.14 0L36.5 16.57L39.98 21.01L40.11 20.89L40.11 2.04L40.23 1.92L45.39 1.92L45.39 19.09L45.51 19.21L48.75 14.77L63.88 14.77ZM30.26 31.22L25.34 31.22L25.22 31.1L25.22 15.25L25.34 15.13L25.94 15.85L30.38 21.73L30.38 31.1Z"
      />
    </svg>
  );
}
